### ISSUE TITLE
After rejecting the project, the automatic email which is sent to the client says that the project has been successfully delivered

### ISSUE THREAD

**Issue by serenesareen** [SpidersTech/Spiders-Companion#2]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by setupspiders** [comment]
@serenesareen Thank you for the bug report. We are closing your issue as we've updated the live site with fix. Please continue sharing your concerns here if needed.
