### ISSUE TITLE
[BUG] Footer Explore Projects quick link directing to home page instead of Explore Project

### ISSUE THREAD

**Issue by AdiNa1211** [SpidersTech/Spiders-Companion#5]
**Describe the bug**
Explore Projects redirecting to home page.

**To Reproduce**
1. Go to 'Explore Projects link in the footer
2. It will redirect to HomePage instead of Explore Projects page.

**Expected behavior**
Kind of obvious , It should redirect to Explore Projects Page.

**GIF**

![spidersexploreprojects](https://user-images.githubusercontent.com/43600925/136988172-b1557def-118c-4f95-a0fd-d69e12e4a232.gif)

**Comment by setupspiders** [comment]
@n0dz Thank you for the bug report. We are closing your issue as we've updated the live site with fix. Please continue sharing your concerns here if needed.
